name: AreCreative
main: me.dngynq.creative.core
version: 1.0
Author: [DngYnQ]

commands:
 donate:
 mygames:
 hub:
 loc:
 gm:
 gamerule:
 settings:
 list:
 dev:
 locate:
 build:
 r:
 reg:
 register:
 l:
 login:
 help:
 profile: